name: 'Upload Android Release to Amazon Appstore'
description: "An action to upload a signed Android release (.apk) to the Amazon Appstore"
author: 'galonga'
branding:
  icon: 'truck'
  color: 'orange'
inputs:
  clientId:
    description: "The client ID of the Amazon AppStore application."
    required: true
  clientSecret:
    description: "The client secret of the Amazon AppStore application."
    required: true
  appId:
    description: "Amazon Appstore app id of the application you are uploading."
    required: true
  releaseFile:
    description: "The Android release file to upload (.apk)"
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'
